### ISSUE TITLE
Racecondition in MdnsPlugin

### ISSUE THREAD

**Issue by gizmomogwai** [platinumjam/flutter_mdns#2]
If startDiscovery is called really quick and something is really quickly discovered/resolved, the internal streamhandler (e.g. mDiscoveredHandler) are not yet initialized.
channel.setMethodCallHandler(this); should be the last call in MdnsPlugin(Registrar r) ...

**Comment by platinumjam** [comment]
Thanks for taking the time to create an issue.

I've pushed the fix you mentioned to the `development` branch. Please take a look and let me know if the issue is resolved.

**Comment by gizmomogwai** [comment]
Thanks for creating this plugin in the first place ... i just started with flutter and was very happy to not have to do it 👍
I tried the fix in my local flutter dependency and this did work (although i only moved registering of the methodcallhandler down. I like your solution more.
Do you know if its possible to pull the development branch in with a pub dependency?

**Comment by platinumjam** [comment]
This seems to work :

**Comment by gizmomogwai** [comment]
Wow ... thats really great. Thank a lot. This will come in handy!

**Comment by platinumjam** [comment]
Closing this unless someone complains
